function ulysses16 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ULYSSES16 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  ULYSSES16 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  ulysses16 = importfile("E:\matlab\tsp\ulysses16.tsp", [8, 23]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Aug-2019 15:19:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Var1", "ulysses16tsp", "VarName3", "Var4"];
opts.SelectedVariableNames = ["ulysses16tsp", "VarName3"];
opts.VariableTypes = ["string", "double", "double", "string"];
opts = setvaropts(opts, [1, 4], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 4], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
ulysses16 = readtable(filename, opts);

%% Convert to output type
ulysses16 = table2array(ulysses16);
end